### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by orchidee247** [urmagicsmine/MP3D#2]
Dear Authors,

I have been trying to download the pretrained MP3D63 model from the BaiduYun link, but wasn´t able to, because of the lack of an account, which is hard to get for a Non-Chinese person. Is there any chance that you could make the model available on any other storage place?

Kind Regards and thank for your help.

**Comment by mproym00** [comment]
Hi,
Happens the same to me, if you found another way to download the pretrained model please tell me how or where.
Thanks in advance.

**Comment by urmagicsmine** [comment]
> Dear Authors,
> 
> I have been trying to download the pretrained MP3D63 model from the BaiduYun link, but wasn´t able to, because of the lack of an account, which is hard to get for a Non-Chinese person. Is there any chance that you could make the model available on any other storage place?
> 
> Kind Regards and thank for your help.

    Sorry to reply you late, we have added the Google Drive link, please refer to README or download it here: https://drive.google.com/file/d/1jKdJQ83vZrvOT4N_iZeRvhDuyKWiboqi/view?usp=sharing
